# 
image: debian:latest

before_script:
  - apt update
  - apt -y install python3-gi python3-gi-cairo gir1.2-gtk-3.0 make python-dev build-essential python3-setuptools python3-pip python3-sphinx python3-sphinx-rtd-theme twine
  - python3 --version  # For debugging
  - rm -rf dist
  - echo "[distutils]" >> ~/.pypirc
  - echo "index-servers =" >> ~/.pypirc
  - echo "" >> ~/.pypirc
  - echo "[pypi]" >> ~/.pypirc
  - echo "username = __token__" >> ~/.pypirc
  - echo "password = ${TWINE_PASSWORD}" >> ~/.pypirc

run:
  only:
    - tags
  except:
    - branches
  script:
    - python3 setup.py sdist 
    - python3 setup.py bdist
    - python3 setup.py bdist_wheel
    - ls dist/*
    - twine check dist/*.whl
    - twine upload --verbose dist/*.whl
    - rm -rf ~/.pypirc
  
  artifacts:
    paths:
      - dist/*

  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'New gResistor release version $CI_COMMIT_TAG '
